### ISSUE TITLE
make up-dev issues

### ISSUE THREAD

**Issue by michalpietron-coderslab** [kreait/slim-php-docker-starter#1]
In dev.yml is mistake in volumes, it should be:
```
version: '2'

services:
  web-frontend:
    volumes:
      - ./web/public:/var/www/html/public
    ports:
      - 80:80
  web-backend:
    volumes:
      - ./web:/var/www/html

```
